# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/nest-asyncio-1.5.5-python_3.10-on-linux_64, last modified Wed Apr 13 10:57:35 2022
# ------------------------------------------------

package:
  name: nest-asyncio
  version: 1.5.5
source:
  sha256: e442291cd942698be619823a17a86a5759eabe1f8613084790de189fe9e16d65
  url: https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.5.5.tar.gz
build:
  number: '0'
  script: /tmp/build/80754af9/nest-asyncio_1649830051683/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.3.29 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1n h7f8727e_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py310h06a4308_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.10.4 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 61.2.0 py310h06a4308_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - setuptools_scm 6.3.2 hd3eb1b0_0
    - sqlite 3.38.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2022a hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - python >=3.10,<3.11.0a0
test:
  imports:
    - nest_asyncio
about:
  description: 'By design asyncio does not allow its event loop to be nested.

    This presents a practical problem - when in an environment where the event loop
    is already running it''s impossible to run tasks and wait for the result.

    Trying to do so will give the error RuntimeError - This event loop is already
    running.

    The issue pops up in various environments, such as web servers, GUI applications
    and in Jupyter notebooks.

    This module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.

    '
  dev_url: https://github.com/erdewit/nest_asyncio
  doc_url: https://github.com/erdewit/nest_asyncio
  home: https://github.com/erdewit/nest_asyncio
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Patch asyncio to allow nested event loops
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - dhirschfeld
    - yehoshuadimarsky
